### ISSUE TITLE
Mismatch in timestamps of .nev file and .ncs file

### ISSUE THREAD

**Issue by rajatsaxena** [alafuzof/NeuralynxIO#1]
When you load a .nev file and .ncs file of a continuously recorded channel the eventMarkers time stamps should be present in the timestamps obtained using .ncs file. But they are not?

Please take a look

**Comment by alafuzof** [comment]
This is issue is probably no longer current, but here's an explanation for future readers (hello, future readers!):

The NCS file only stores timestamps every 512 samples. The load_ncs function will return a full array of timestamps (one for each sample), but these are interpolated between the specified values. Thus, the timestamps recorded for an event may not perfectly match up with the interpolated values. There might also be another mismatch, if event are timestamped, when they occur, and not during the next sampling time. I suggest you simply take the sample nearest the event timestamp and work with that.
